name: icontesting
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  confetti: ^0.8.0
  flutter:
    sdk: flutter
  page_flip: ^0.2.3
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/videos/

  fonts:
    - family: cursive     
      fonts:
        - asset: assets/fonts/Allura-Regular.ttf

